Updated discombobulator
MinecraftTAS/LoTAS pull request #86
Opened 2023-02-21 15:39 UTC by ScribbleLP

- Removed version specific accesswideners
- Updated patterns in code to include a ;

2023-02-21 18:24 UTC, MCPfannkuchenYT requested changes
Fix preprocessor things I annotated

2023-02-21 18:24 UTC, MCPfannkuchenYT commented on src/main/resources/lotas.accesswidener
> +## end
Why is there an empty "#def" block, can't it just be "#end"?

2023-02-21 18:24 UTC, MCPfannkuchenYT commented on src/main/resources/lotas.accesswidener
> +## end
again

2023-02-21 18:24 UTC, MCPfannkuchenYT commented on src/main/resources/lotas.accesswidener
> +## end
again

2023-02-21 18:24 UTC, MCPfannkuchenYT commented on src/main/resources/lotas.accesswidener
> +## end
again

2023-02-21 18:24 UTC, MCPfannkuchenYT commented on src/main/resources/lotas.accesswidener
> +## end
again

2023-02-25 08:44 UTC, MCPfannkuchenYT approved these changes
Thanks. Is it ready to merge now?

2023-02-25 08:45 UTC, ScribbleLP commented
nope

2023-02-27 22:56 UTC, merged